# NumPy Searching Arrays

In [2]:
# Searching Arrays
    # - search an array for a certain value, and return the indexes that get a match.
    # - use the where() method.
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [3]:
# Find the indexes where the values are even:
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [4]:
# Find the indexes where the values are odd:
x = np.where(arr % 2 == 1)
print(x)

(array([0, 2, 4], dtype=int64),)


# Search Sorted

In [5]:
# Search Sorted
    # - There is a method called searchsorted() 
    # - performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
# Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

arr = np.array([2,3,4,6])
x = np.searchsorted(arr, 5)
print(x)

x = np.searchsorted(arr, 7)
print(x)

1
3
4


# searchsorted() 

In [6]:
# searchsorted() 

arr = np.array([6,6,4, 7,9,5,5, 8,9, 9]) #4 5 5 6 6 7 8 9 9

x = np.searchsorted(arr, 7, side = 'right')
print(x) 

arr = np.array([6,6,4, 7,9,5,5, 8, 9]) #4 5 5 6 6 7 8 9 9
x = np.searchsorted(arr, 7, side = 'left')
print(x) 



7
3


In [7]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


# Multiple Values

In [8]:
#Multiple Values
    # - To search for more than one value, use an array with the specified values.
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)




[1 2 3]
