# Sorting Arrays
Note: This method returns a copy of the array, leaving the original array unchanged.



In [1]:
# Sorting Arrays
    # - Sorting means putting elements in an ordered sequence.
    # - object has a function called sort()
import numpy as np 
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [2]:
# Sort the array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [3]:
# Sort a boolean array:
arr = np.array([True, False, True])

print(np.sort(arr))


[False  True  True]


# Sorting a 2-D Array

In [5]:
# Sorting a 2-D Array    
    # - both arrays will be sorted
arr = np.array([[3, 6, 5], [7, 6, 8]])
print(np.sort(arr))

[[3 5 6]
 [6 7 8]]
