<-- NumPy -->

- it's a python library
- it's used for working with arrays
- NumPy -> Numerical python
-working in domain of linear algebra, fourier transform, and matrices.
- created in 2005 by Travis Oliphant
- It is an open source project

<!-- Why Use NumPy -->
-  NumPy is called ndarray
- In Python we have lists that serve the purpose of arrays, but they are slow to process

<!-- Why is NumPy Faster Than Lists -->

-arrays are stored at one continuous place in memory unlike list

In [2]:
# Installation of NumPy
# pip install numpy

SyntaxError: invalid syntax (2947115696.py, line 2)

In [12]:
# Import NumPy and NumPy as np

import numpy as np
arr = np.array([1,2,3,8,4,5])
print(arr)



[1 2 3 4 5]


In [5]:
# Checking NumPy Version
print(np.__version__)

1.26.4


In [13]:
# Create a NumPy ndarray Object
arr = np.array([1,2,3,4,5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
# tuple to create a NumPy array:

arr = np.array((1,2,3,4,5))
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
# Dimensions in Arrays

# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(42)
print(arr)

#1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
# NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

arr = np.array([1,2,3,4,5])
print(arr)

# 2D-array or matrix
# An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1,2,3,4], [1,6,8,5]])
print(arr)

#3D-array 
arr = np.array([[[1, 2, 4],[3,4,5],[5,6,7]],[[12,3,4],[6,4,5],[4,3,4]]])
print(arr)

42
[1 2 3 4 5]
[[1 2 3 4]
 [1 6 8 5]]
[[[ 1  2  4]
  [ 3  4  5]
  [ 5  6  7]]

 [[12  3  4]
  [ 6  4  5]
  [ 4  3  4]]]


In [9]:
# Check Number of Dimensions
# NumPy Arrays provides the "ndim" attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
print(a.ndim)

b = np.array([1,2,3,4])
print(b.ndim)

c = np.array([[1,2,3],[2,3,4]])
print(c.ndim)

d = np.array([[[1,2,3],[1,2,3]], [[2,1,2],[6,5,7]]])
print(d.ndim)

e = np.array([[[[1,2],[3,2]],[[3,4],[3,4]],[[2,1],[4,5]],[[2,1],[5,4]]]])
print(e.ndim)


0
1
2
3
4


In [10]:
# Higher Dimensional Arrays
# - An array can have any number of dimensions.
# - using the "ndmin" argument.

arr = np.array([1,2,3,4,5,6], ndmin = 5)
print(arr)

print(f'number of dimension : {arr.ndim}')

[[[[[1 2 3 4 5 6]]]]]
number of dimension : 5
