In [1]:
# NumPy Array Slicing
# - taking elements from one given index to another given index.
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].

import numpy as np

arr = np.array([1,2,4,3,5])
print(arr[0:3])
print(arr[::-1])
print(arr[-2:])
print(arr[:-3])
print(arr[:3])
print(arr[2:])
print(arr[::2])
print(arr[0:5:2])


[1 2 4]
[5 3 4 2 1]
[3 5]
[1 2]
[1 2 4]
[4 3 5]
[1 4 5]
[1 4 5]


In [2]:
# Slicing 2-D Arrays

arr = np.array([[1,2,3,4],[4,5,6,7]])

# From the second element, slice elements from index 1 to index 4 (not included)
print(arr[1, 1:4])

# both elements, return index 2 or else :
print(arr[0:2, 2])
print(arr[:1, 1])


# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1,2,3,4,5],[9,8,7,6,4]])
print(arr[0:2, 1:5])


[5 6 7]
[3 6]
[2]
[[2 3 4 5]
 [8 7 6 4]]
