In [1]:
# The Difference Between Copy and View
    # copy is a new array, and the view is just a view of the original array.

import numpy as np 

arr = np.array([1,2,3,4,5])
x = arr.copy() 
arr[0] = 42 # only change the original array

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
# VIEW
# Make a view, change the original array, and display both arrays:
x = arr.view()
arr[0] = 42 

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [11]:
# Check if Array Owns it's Data
arr = np.array([1,2,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 4 5]
