In [1]:
# Array Shape
    # The shape of an array is the number of elements in each dimension.

# Get the Shape of an Array
    # "shape" that returns a tuple with each index having the number of corresponding elements.
import numpy as np
 
arr = np.array([[1,2,3],[6,7,9]])
print(arr.shape)


arr = np.array([1,2,3,4], ndmin = 6)
print(arr)
print('hape of array:', arr.shape)

arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print('hape of array:', arr.shape)




(2, 3)
[[[[[[1 2 3 4]]]]]]
hape of array: (1, 1, 1, 1, 1, 4)
[[[[[1 2 3 4]]]]]
hape of array: (1, 1, 1, 1, 4)


In [12]:
# Use the correct NumPy method to change the shape of an array from 1-D to 2-D.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

newarr1 = arr.reshape(2, 3, 2)
print(newarr1)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
# Returns Copy or View?
import numpy as np 
 
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2, 4).base) #returns the original array, so it is a view

[1 2 3 4 5 6 7 8]


In [4]:
#Unknown Dimension
    #  - do not have to specify an exact number for one of the dimensions in the reshape method.
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-4)
print(newarr)

print("=======================")
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,4)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
# Flattening the arrays -> converting a multidimensional array into a 1D array
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]
