# Array Iterating

In [1]:
# Array Iterating
    # - Iterating means going through elements one by one.
# Iterate on the elements of the following 1-D array:
import numpy as np
arr = np.array([1,2,3])
for x in arr:
    print(x)



1
2
3


In [3]:
# Iterating 2-D Arrays
arr = np.array([[1,2,3,4],[5,6,7,9]])
for x in arr:
    print(x)
print("====================")
for x in arr:
    for y in x:
        print(y)

[1 2 3 4]
[5 6 7 9]
1
2
3
4
5
6
7
9


In [5]:
# Iterating 3-D Arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x) 

print("==============================")
for x in arr:
    for y in x:
        for z in y:
            print(z) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [6]:
# Iterating Arrays Using nditer()
    # - used from very basic to very advanced iterations
    # - solves some basic issues

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

In [10]:
# Iterating Array With Different Data Types
    # - "op_dtypes" ->use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating
    # - extra space is called buffer
    # -order to enable it in nditer() we pass flags=['buffered'].

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes = 'S'):
    print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


# Iterating With Different Step Size

In [11]:
# Iterating With Different Step Size

arr = np.array([[1,2,3,4], [5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x) 

1
3
5
7


# Enumerated Iteration Using ndenumerate()

In [17]:
# Enumerated Iteration Using ndenumerate()
    # - mentioning sequence number of somethings one by one

# 1D arrays elements
print('for 1D array')
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x) 




for 1D array
(0,) 1
(1,) 2
(2,) 3


In [2]:
import numpy as np
print("for 2D array")
arr = np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x) 

for 2D array
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
