# Joining NumPy Arrays

In [35]:
# Joining NumPy Arrays
    # - means putting contents of two or more arrays in a single array
    # -want to join to the concatenate() function
import numpy as np

print("For 1D array")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

For 1D array
[1 2 3 4 5 6]


In [33]:
print("For 2D array")
arr1 = np.array([[1,3],[4,5]])
arr2 = np.array([[5,6],[7,6]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr) 

For 2D array
[[1 3 5 6]
 [4 5 7 6]]


In [7]:
import numpy as np
print("For 3D array")
arr1 = np.array([[[1,2],[3,4]], [[5,6],[9,8]]])
arr2 = np.array([[[4,3],[7,8]], [[9,7],[4,7]]])
arr = np.concatenate((arr1, arr2), axis = 2)
print(arr) 


For 3D array
[[[1 2 4 3]
  [3 4 7 8]]

 [[5 6 9 7]
  [9 8 4 7]]]


# Joining Arrays Using Stack Functions

In [ ]:
# Joining Arrays Using Stack Functions
    # - Stacking is same as concatenation
    # - only difference is that stacking is done along a new axis.
    # - we want to join to the stack() method along with the axis
    # -  If axis is not explicitly passed it is taken as 0.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)



[[1 2 3]
 [4 5 6]]


In [9]:
# Stacking Along Rows
    # - hstack() to stack along rows
print("Stacking Along Rows")

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print()

Stacking Along Rows
[1 2 3 4 5 6]



In [30]:
# Stacking Along Columns
    # - vstack()  to stack along columns.
print("Stacking Along Columns")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)


Stacking Along Columns
[[1 2 3]
 [4 5 6]]


In [32]:
# Stacking Along Height (depth)
    #  - dstack() to stack along height, which is the same as depth.

print("For 1D array")
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

For 1D array
[[[1 4]
  [2 5]
  [3 6]]]


In [31]:
print("For 2D array")
arr1 = np.array([[1, 2, 3],[6, 7, 8]])
arr2 = np.array([[4, 5, 6], [4, 5, 6]])
arr = np.dstack((arr1, arr2))
print(arr)

For 2D array
[[[1 4]
  [2 5]
  [3 6]]

 [[6 4]
  [7 5]
  [8 6]]]
