# NumPy Splitting Array

In [1]:
# Splitting NumPy Arrays
    # - Splitting is reverse operation of Joining.
    # - Joining merges multiple arrays into one and Splitting breaks one array into multiple.
# "array_split()"

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr)

newarr = np.split(arr, 3)
print(newarr)

newarr = np.split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


ValueError: array split does not result in an equal division

# Split Into Arrays

In [2]:
# Access the splitted arrays

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays

In [10]:
arr = np.array([[1, 2],[3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
  
newarr = np.split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [11]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [4]:
# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis = 1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [9]:
# An alternate solution is using hsplit() opposite of hstack()
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr,3)
print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [11]:
# Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().
#vstack() 
newarr = np.vstack(arr)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [13]:
#dstack()
newarr = np.dstack(arr)
print(newarr)

[[[ 1  4  7 10 13 16]
  [ 2  5  8 11 14 17]
  [ 3  6  9 12 15 18]]]


In [15]:
#vsplit()
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [24]:
#dsplit()
newarr = np.dsplit(arr, 5)
print(newarr)

ValueError: dsplit only works on arrays of 3 or more dimensions